<?php
/*
 * Settings metadata file
 */

return array(
  'opt_in' => array(
    'group_name' => 'BSD API Preferences',
    'group' => 'bsd_api',
    'name' => 'opt_in',
    'type' => 'Boolean',
    'quick_form_type' => 'YesNo',
    'html_type' => 'checkbox',
    'default' => 1,
    'add' => '4.6',
    'is_domain' => 1,
    'is_contact' => 0,
    'title' => 'Opt-in',
    'description' => "Opt-in",
    'help_text' => "Opt-in",
  ),
  'group_id' => array(
    'group_name' => 'BSD API Preferences',
    'group' => 'bsd_api',
    'name' => 'group_id',
    'type' => 'Integer',
    'default' => 42,
    'add' => '4.6',
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => 'Default group',
    'help_text' => 'Default group',
  ),
  'default_template_id' => array(
    'group_name' => 'BSD API Preferences',
    'group' => 'bsd_api',
    'name' => 'default_template_id',
    'type' => 'Integer',
    'default' => 69,
    'add' => '4.6',
    'is_domain' => 1,
    'is_contact' => 0,
    'title' => 'Default template',
    'description' => "Default message template id",
    'help_text' => "Default message template id",
  ),
  'default_language' => array(
    'group_name' => 'BSD API Preferences',
    'group' => 'bsd_api',
    'name' => 'default_language',
    'type' => 'String',
    'default' => 'en_US',
    'add' => '4.6',
    'is_domain' => 1,
    'is_contact' => 0,
    'title' => 'Default language',
    'description' => "Default language",
    'help_text' => "Default language",
  ),
  'field_template_id' => array(
    'group_name' => 'BSD API Preferences',
    'group' => 'bsd_api',
    'name' => 'field_template_id',
    'type' => 'String',
    'default' => 'custom_3',
    'add' => '4.6',
    'is_domain' => 1,
    'is_contact' => 0,
    'title' => 'Custom field for campaign\'s message template',
    'description' => "Custom field for campaign's message template",
    'help_text' => "Custom field for campaign's message template",
  ),
  'field_language' => array(
    'group_name' => 'BSD API Preferences',
    'group' => 'bsd_api',
    'name' => 'field_language',
    'type' => 'String',
    'default' => 'custom_4',
    'add' => '4.6',
    'is_domain' => 1,
    'is_contact' => 0,
    'title' => 'Custom field for campaign\'s language',
    'description' => "Custom field for campaign's language",
    'help_text' => "Custom field for campaign's language",
  ),
  'from' => array(
    'group_name' => 'BSD API Preferences',
    'group' => 'bsd_api',
    'name' => 'from',
    'type' => 'String',
    'default' => '"Xavier - WeMove.EU" <info@wemove.eu>',
    'add' => '4.6',
    'is_domain' => 1,
    'is_contact' => 0,
    'title' => 'From',
    'description' => "From",
    'help_text' => "From",
  ),
  'country_lang_mapping' => array(
    'group_name' => 'BSD API Preferences',
    'group' => 'bsd_api',
    'name' => 'country_lang_mapping',
    'type' => 'Array',
    'default' => array(
      'DE' => 'de_DE',
      'EN' => 'en_US',
      'ES' => 'es_ES',
      'FR' => 'fr_FR',
      'IT' => 'it_IT',
      'PL' => 'pl_PL',
    ),
    'add' => '4.6',
    'is_domain' => 1,
    'is_contact' => 0,
    'title' => 'Mapping between country code and language',
    'description' => "Mapping between country code and language",
    'help_text' => "Mapping between country code and language",
  ),
  'notconfirmation' => array(
    'group_name' => 'BSD API Preferences',
    'group' => 'bsd_api',
    'name' => 'notconfirmation',
    'type' => 'Array',
    'default' => array(9),
    'add' => '4.6',
    'is_domain' => 1,
    'is_contact' => 0,
    'title' => 'External campaigns id for not confirmation',
    'description' => "External campaigns id for not confirmation",
    'help_text' => "External campaigns id for not confirmation",
  ),
);
